#include "cog.h"

#include <parse/default.h>

namespace parse
{

void cog_t::load(grammar_t &grammar)
{
	COG = grammar.rules.size();
	grammar.rules.push_back(rule_t(COG, "cog::cog", true));
	STRUCTDEF = grammar.rules.size();
	grammar.rules.push_back(rule_t(STRUCTDEF, "cog::structdef", true));
	FUNCTIONDEF = grammar.rules.size();
	grammar.rules.push_back(rule_t(FUNCTIONDEF, "cog::functiondef", true));
	OUTDECL = grammar.rules.size();
	grammar.rules.push_back(rule_t(OUTDECL, "cog::outdecl", true));
	TYPENAME = grammar.rules.size();
	grammar.rules.push_back(rule_t(TYPENAME, "cog::typename", true));
	INDECL = grammar.rules.size();
	grammar.rules.push_back(rule_t(INDECL, "cog::indecl", true));
	BLOCK = grammar.rules.size();
	grammar.rules.push_back(rule_t(BLOCK, "cog::block", true));
	STATEMENT = grammar.rules.size();
	grammar.rules.push_back(rule_t(STATEMENT, "cog::statement", true));
	EXPRESSION = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXPRESSION, "cog::expression", true));
	IF_STMT = grammar.rules.size();
	grammar.rules.push_back(rule_t(IF_STMT, "cog::if_stmt", true));
	WHILE_LOOP = grammar.rules.size();
	grammar.rules.push_back(rule_t(WHILE_LOOP, "cog::while_loop", true));
	ASSIGN = grammar.rules.size();
	grammar.rules.push_back(rule_t(ASSIGN, "cog::assign", true));
	EXP13 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP13, "cog::exp13", true));
	EXP12 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP12, "cog::exp12", true));
	EXP11 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP11, "cog::exp11", true));
	EXP10 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP10, "cog::exp10", true));
	EXP9 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP9, "cog::exp9", true));
	EXP8 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP8, "cog::exp8", true));
	EXP7 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP7, "cog::exp7", true));
	EXP6 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP6, "cog::exp6", true));
	EXP5 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP5, "cog::exp5", true));
	EXP4 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP4, "cog::exp4", true));
	EXP2 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP2, "cog::exp2", true));
	CONSTANT = grammar.rules.size();
	grammar.rules.push_back(rule_t(CONSTANT, "cog::constant", true));
	EXP1 = grammar.rules.size();
	grammar.rules.push_back(rule_t(EXP1, "cog::exp1", true));
	BOOL = grammar.rules.size();
	grammar.rules.push_back(rule_t(BOOL, "cog::bool", true));
	INT = grammar.rules.size();
	grammar.rules.push_back(rule_t(INT, "cog::int", true));
	STRING = grammar.rules.size();
	grammar.rules.push_back(rule_t(STRING, "cog::string", true));
	REAL = grammar.rules.size();
	grammar.rules.push_back(rule_t(REAL, "cog::real", true));

	symbol_t *n[300];
	n[0] = grammar.insert(new instance(true));
	n[1] = grammar.insert(new whitespace(true, false));
	n[2] = grammar.insert(new keyword("::", true));
	n[3] = grammar.insert(new whitespace(true, false));
	n[4] = grammar.insert(new instance(true));
	n[5] = grammar.insert(new keyword("void", true));
	n[6] = grammar.insert(new integer(10, true));
	n[7] = grammar.insert(new keyword("float", true));
	n[8] = grammar.insert(new integer(10, true));
	n[9] = grammar.insert(new keyword("e", false));
	n[10] = grammar.insert(new integer(10, true));
	n[11] = grammar.insert(new keyword("ufixed", true));
	n[12] = grammar.insert(new keyword("fixed", true));
	n[13] = grammar.insert(new integer(10, true));
	n[14] = grammar.insert(new keyword("uint", true));
	n[15] = grammar.insert(new keyword("int", true));
	n[16] = grammar.insert(new keyword("bool", true));
	n[17] = grammar.insert(new text(false));
	n[18] = grammar.insert(new integer(10, true));
	n[19] = grammar.insert(new keyword("-", true));
	n[20] = grammar.insert(new keyword("e", true));
	n[21] = grammar.insert(new integer(10, true));
	n[22] = grammar.insert(new keyword(".", true));
	n[23] = grammar.insert(new integer(10, true));
	n[24] = grammar.insert(new integer(10, true));
	n[25] = grammar.insert(new integer(2, true));
	n[26] = grammar.insert(new keyword("0b", true));
	n[27] = grammar.insert(new integer(16, true));
	n[28] = grammar.insert(new keyword("0x", true));
	n[29] = grammar.insert(new keyword("false", false));
	n[30] = grammar.insert(new keyword("true", false));
	n[31] = grammar.insert(new stem(28, true));
	n[32] = grammar.insert(new stem(27, true));
	n[33] = grammar.insert(new stem(26, true));
	n[34] = grammar.insert(new stem(25, true));
	n[35] = grammar.insert(new instance(true));
	n[36] = grammar.insert(new keyword(")", true));
	n[37] = grammar.insert(new whitespace(true, false));
	n[38] = grammar.insert(new stem(8, true));
	n[39] = grammar.insert(new whitespace(true, false));
	n[40] = grammar.insert(new keyword("(", true));
	n[41] = grammar.insert(new stem(24, true));
	n[42] = grammar.insert(new whitespace(true, false));
	n[43] = grammar.insert(new keyword(".", true));
	n[44] = grammar.insert(new keyword("@", true));
	n[45] = grammar.insert(new keyword("#", true));
	n[46] = grammar.insert(new keyword("]", true));
	n[47] = grammar.insert(new whitespace(true, false));
	n[48] = grammar.insert(new stem(8, true));
	n[49] = grammar.insert(new whitespace(true, false));
	n[50] = grammar.insert(new keyword(":", true));
	n[51] = grammar.insert(new whitespace(true, false));
	n[52] = grammar.insert(new stem(8, true));
	n[53] = grammar.insert(new whitespace(true, false));
	n[54] = grammar.insert(new keyword("[", true));
	n[55] = grammar.insert(new keyword(")", true));
	n[56] = grammar.insert(new whitespace(true, false));
	n[57] = grammar.insert(new stem(8, true));
	n[58] = grammar.insert(new whitespace(true, false));
	n[59] = grammar.insert(new keyword(",", true));
	n[60] = grammar.insert(new whitespace(true, false));
	n[61] = grammar.insert(new stem(8, true));
	n[62] = grammar.insert(new whitespace(true, false));
	n[63] = grammar.insert(new keyword("(", true));
	n[64] = grammar.insert(new whitespace(true, false));
	n[65] = grammar.insert(new stem(24, true));
	n[66] = grammar.insert(new stem(23, true));
	n[67] = grammar.insert(new stem(22, true));
	n[68] = grammar.insert(new whitespace(true, false));
	n[69] = grammar.insert(new keyword("~", true));
	n[70] = grammar.insert(new keyword("not", true));
	n[71] = grammar.insert(new keyword("-", true));
	n[72] = grammar.insert(new stem(21, true));
	n[73] = grammar.insert(new whitespace(true, false));
	n[74] = grammar.insert(new keyword("%", true));
	n[75] = grammar.insert(new keyword("/", true));
	n[76] = grammar.insert(new keyword("*", true));
	n[77] = grammar.insert(new whitespace(true, false));
	n[78] = grammar.insert(new stem(21, true));
	n[79] = grammar.insert(new stem(20, true));
	n[80] = grammar.insert(new whitespace(true, false));
	n[81] = grammar.insert(new keyword("-", true));
	n[82] = grammar.insert(new keyword("+", true));
	n[83] = grammar.insert(new whitespace(true, false));
	n[84] = grammar.insert(new stem(20, true));
	n[85] = grammar.insert(new stem(19, true));
	n[86] = grammar.insert(new whitespace(true, false));
	n[87] = grammar.insert(new keyword(">><", true));
	n[88] = grammar.insert(new keyword("<<>", true));
	n[89] = grammar.insert(new keyword(">>>", true));
	n[90] = grammar.insert(new keyword(">>", true));
	n[91] = grammar.insert(new keyword("<<", true));
	n[92] = grammar.insert(new whitespace(true, false));
	n[93] = grammar.insert(new stem(19, true));
	n[94] = grammar.insert(new stem(18, true));
	n[95] = grammar.insert(new whitespace(true, false));
	n[96] = grammar.insert(new keyword("&", true));
	n[97] = grammar.insert(new whitespace(true, false));
	n[98] = grammar.insert(new stem(18, true));
	n[99] = grammar.insert(new stem(17, true));
	n[100] = grammar.insert(new whitespace(true, false));
	n[101] = grammar.insert(new keyword("^", true));
	n[102] = grammar.insert(new whitespace(true, false));
	n[103] = grammar.insert(new stem(17, true));
	n[104] = grammar.insert(new stem(16, true));
	n[105] = grammar.insert(new whitespace(true, false));
	n[106] = grammar.insert(new keyword("|", true));
	n[107] = grammar.insert(new whitespace(true, false));
	n[108] = grammar.insert(new stem(16, true));
	n[109] = grammar.insert(new stem(15, true));
	n[110] = grammar.insert(new whitespace(true, false));
	n[111] = grammar.insert(new keyword("!=", true));
	n[112] = grammar.insert(new keyword("==", true));
	n[113] = grammar.insert(new keyword(">=", true));
	n[114] = grammar.insert(new keyword("<=", true));
	n[115] = grammar.insert(new keyword(">", true));
	n[116] = grammar.insert(new keyword("<", true));
	n[117] = grammar.insert(new whitespace(true, false));
	n[118] = grammar.insert(new stem(15, true));
	n[119] = grammar.insert(new stem(14, true));
	n[120] = grammar.insert(new whitespace(true, false));
	n[121] = grammar.insert(new keyword("and", true));
	n[122] = grammar.insert(new whitespace(true, false));
	n[123] = grammar.insert(new stem(14, true));
	n[124] = grammar.insert(new stem(13, true));
	n[125] = grammar.insert(new whitespace(true, false));
	n[126] = grammar.insert(new keyword("xor", true));
	n[127] = grammar.insert(new whitespace(true, false));
	n[128] = grammar.insert(new stem(13, true));
	n[129] = grammar.insert(new stem(12, true));
	n[130] = grammar.insert(new whitespace(true, false));
	n[131] = grammar.insert(new keyword("or", true));
	n[132] = grammar.insert(new whitespace(true, false));
	n[133] = grammar.insert(new stem(12, true));
	n[134] = grammar.insert(new keyword("]", true));
	n[135] = grammar.insert(new whitespace(true, false));
	n[136] = grammar.insert(new stem(8, true));
	n[137] = grammar.insert(new whitespace(true, false));
	n[138] = grammar.insert(new keyword("[", true));
	n[139] = grammar.insert(new whitespace(true, false));
	n[140] = grammar.insert(new instance(true));
	n[141] = grammar.insert(new whitespace(true, false));
	n[142] = grammar.insert(new keyword(",", true));
	n[143] = grammar.insert(new whitespace(true, false));
	n[144] = grammar.insert(new keyword("]", true));
	n[145] = grammar.insert(new whitespace(true, false));
	n[146] = grammar.insert(new stem(8, true));
	n[147] = grammar.insert(new whitespace(true, false));
	n[148] = grammar.insert(new keyword("[", true));
	n[149] = grammar.insert(new whitespace(true, false));
	n[150] = grammar.insert(new instance(true));
	n[151] = grammar.insert(new whitespace(true, false));
	n[152] = grammar.insert(new stem(4, true));
	n[153] = grammar.insert(new stem(8, true));
	n[154] = grammar.insert(new keyword("=", true));
	n[155] = grammar.insert(new whitespace(true, false));
	n[156] = grammar.insert(new keyword("]", false));
	n[157] = grammar.insert(new whitespace(true, false));
	n[158] = grammar.insert(new stem(8, true));
	n[159] = grammar.insert(new whitespace(true, false));
	n[160] = grammar.insert(new keyword("[", true));
	n[161] = grammar.insert(new whitespace(true, false));
	n[162] = grammar.insert(new instance(true));
	n[163] = grammar.insert(new whitespace(true, false));
	n[164] = grammar.insert(new keyword(",", false));
	n[165] = grammar.insert(new whitespace(true, false));
	n[166] = grammar.insert(new stem(8, true));
	n[167] = grammar.insert(new keyword("=", true));
	n[168] = grammar.insert(new whitespace(true, false));
	n[169] = grammar.insert(new keyword("#", true));
	n[170] = grammar.insert(new whitespace(true, false));
	n[171] = grammar.insert(new keyword("]", false));
	n[172] = grammar.insert(new whitespace(true, false));
	n[173] = grammar.insert(new stem(8, true));
	n[174] = grammar.insert(new whitespace(true, false));
	n[175] = grammar.insert(new keyword("[", true));
	n[176] = grammar.insert(new whitespace(true, false));
	n[177] = grammar.insert(new instance(true));
	n[178] = grammar.insert(new whitespace(true, false));
	n[179] = grammar.insert(new stem(4, true));
	n[180] = grammar.insert(new stem(8, true));
	n[181] = grammar.insert(new whitespace(true, false));
	n[182] = grammar.insert(new keyword("or=", true));
	n[183] = grammar.insert(new keyword("xor=", true));
	n[184] = grammar.insert(new keyword("and=", true));
	n[185] = grammar.insert(new keyword("|=", true));
	n[186] = grammar.insert(new keyword("^=", true));
	n[187] = grammar.insert(new keyword("&=", true));
	n[188] = grammar.insert(new keyword(">><=", true));
	n[189] = grammar.insert(new keyword("<<>=", true));
	n[190] = grammar.insert(new keyword(">>>=", true));
	n[191] = grammar.insert(new keyword(">>=", true));
	n[192] = grammar.insert(new keyword("<<=", true));
	n[193] = grammar.insert(new keyword("%=", true));
	n[194] = grammar.insert(new keyword("/=", true));
	n[195] = grammar.insert(new keyword("*=", true));
	n[196] = grammar.insert(new keyword("-=", true));
	n[197] = grammar.insert(new keyword("+=", true));
	n[198] = grammar.insert(new keyword("=", true));
	n[199] = grammar.insert(new whitespace(true, false));
	n[200] = grammar.insert(new stem(8, true));
	n[201] = grammar.insert(new stem(7, true));
	n[202] = grammar.insert(new stem(6, true));
	n[203] = grammar.insert(new whitespace(true, false));
	n[204] = grammar.insert(new keyword("else", true));
	n[205] = grammar.insert(new whitespace(true, false));
	n[206] = grammar.insert(new stem(7, true));
	n[207] = grammar.insert(new stem(6, true));
	n[208] = grammar.insert(new whitespace(true, false));
	n[209] = grammar.insert(new keyword(")", true));
	n[210] = grammar.insert(new whitespace(true, false));
	n[211] = grammar.insert(new stem(8, true));
	n[212] = grammar.insert(new whitespace(true, false));
	n[213] = grammar.insert(new keyword("(", true));
	n[214] = grammar.insert(new whitespace(true, false));
	n[215] = grammar.insert(new keyword("if", true));
	n[216] = grammar.insert(new whitespace(true, false));
	n[217] = grammar.insert(new keyword("else", true));
	n[218] = grammar.insert(new whitespace(true, false));
	n[219] = grammar.insert(new stem(7, true));
	n[220] = grammar.insert(new stem(6, true));
	n[221] = grammar.insert(new whitespace(true, false));
	n[222] = grammar.insert(new keyword(")", true));
	n[223] = grammar.insert(new whitespace(true, false));
	n[224] = grammar.insert(new stem(8, true));
	n[225] = grammar.insert(new whitespace(true, false));
	n[226] = grammar.insert(new keyword("(", true));
	n[227] = grammar.insert(new whitespace(true, false));
	n[228] = grammar.insert(new keyword("if", true));
	n[229] = grammar.insert(new stem(7, true));
	n[230] = grammar.insert(new stem(6, true));
	n[231] = grammar.insert(new whitespace(true, false));
	n[232] = grammar.insert(new keyword(")", true));
	n[233] = grammar.insert(new whitespace(true, false));
	n[234] = grammar.insert(new stem(8, true));
	n[235] = grammar.insert(new whitespace(true, false));
	n[236] = grammar.insert(new keyword("(", true));
	n[237] = grammar.insert(new whitespace(true, false));
	n[238] = grammar.insert(new keyword("while", true));
	n[239] = grammar.insert(new keyword(";", true));
	n[240] = grammar.insert(new whitespace(true, false));
	n[241] = grammar.insert(new stem(11, true));
	n[242] = grammar.insert(new keyword(";", true));
	n[243] = grammar.insert(new whitespace(true, false));
	n[244] = grammar.insert(new stem(5, true));
	n[245] = grammar.insert(new stem(10, true));
	n[246] = grammar.insert(new stem(9, true));
	n[247] = grammar.insert(new keyword(";", true));
	n[248] = grammar.insert(new whitespace(true, false));
	n[249] = grammar.insert(new stem(8, true));
	n[250] = grammar.insert(new whitespace(true, false));
	n[251] = grammar.insert(new keyword("return", true));
	n[252] = grammar.insert(new keyword(";", true));
	n[253] = grammar.insert(new whitespace(true, false));
	n[254] = grammar.insert(new keyword("continue", true));
	n[255] = grammar.insert(new keyword(";", true));
	n[256] = grammar.insert(new whitespace(true, false));
	n[257] = grammar.insert(new keyword("break", true));
	n[258] = grammar.insert(new keyword("}", true));
	n[259] = grammar.insert(new whitespace(true, false));
	n[260] = grammar.insert(new stem(7, true));
	n[261] = grammar.insert(new whitespace(true, false));
	n[262] = grammar.insert(new stem(7, true));
	n[263] = grammar.insert(new whitespace(true, false));
	n[264] = grammar.insert(new keyword("{", true));
	n[265] = grammar.insert(new stem(6, true));
	n[266] = grammar.insert(new whitespace(true, false));
	n[267] = grammar.insert(new keyword(")", false));
	n[268] = grammar.insert(new whitespace(true, false));
	n[269] = grammar.insert(new stem(5, true));
	n[270] = grammar.insert(new whitespace(true, false));
	n[271] = grammar.insert(new keyword(";", false));
	n[272] = grammar.insert(new whitespace(true, false));
	n[273] = grammar.insert(new stem(5, true));
	n[274] = grammar.insert(new whitespace(true, false));
	n[275] = grammar.insert(new keyword("(", false));
	n[276] = grammar.insert(new whitespace(true, false));
	n[277] = grammar.insert(new instance(true));
	n[278] = grammar.insert(new whitespace(true, false));
	n[279] = grammar.insert(new keyword("::", false));
	n[280] = grammar.insert(new whitespace(true, false));
	n[281] = grammar.insert(new stem(4, true));
	n[282] = grammar.insert(new whitespace(true, false));
	n[283] = grammar.insert(new stem(4, true));
	n[284] = grammar.insert(new keyword("}", true));
	n[285] = grammar.insert(new whitespace(true, false));
	n[286] = grammar.insert(new keyword(";", true));
	n[287] = grammar.insert(new whitespace(true, false));
	n[288] = grammar.insert(new stem(3, true));
	n[289] = grammar.insert(new whitespace(true, false));
	n[290] = grammar.insert(new keyword("{", true));
	n[291] = grammar.insert(new whitespace(true, false));
	n[292] = grammar.insert(new instance(true));
	n[293] = grammar.insert(new whitespace(true, false));
	n[294] = grammar.insert(new keyword("struct", true));
	n[295] = grammar.insert(new character("\\0", true));
	n[296] = grammar.insert(new whitespace(true, false));
	n[297] = grammar.insert(new stem(2, true));
	n[298] = grammar.insert(new stem(1, true));
	n[299] = grammar.insert(new whitespace(true, false));

	n[0]->next.push_back(n[3]);
	n[0]->next.push_back(NULL);
	n[1]->next.push_back(n[0]);
	n[2]->next.push_back(n[1]);
	n[3]->next.push_back(n[2]);
	n[4]->next.push_back(n[3]);
	n[4]->next.push_back(NULL);
	n[5]->next.push_back(NULL);
	n[6]->next.push_back(NULL);
	n[7]->next.push_back(n[6]);
	n[7]->next.push_back(NULL);
	n[8]->next.push_back(NULL);
	n[9]->next.push_back(n[8]);
	n[10]->next.push_back(n[9]);
	n[10]->next.push_back(NULL);
	n[11]->next.push_back(n[10]);
	n[11]->next.push_back(NULL);
	n[12]->next.push_back(n[10]);
	n[12]->next.push_back(NULL);
	n[13]->next.push_back(NULL);
	n[14]->next.push_back(n[13]);
	n[14]->next.push_back(NULL);
	n[15]->next.push_back(n[13]);
	n[15]->next.push_back(NULL);
	n[16]->next.push_back(NULL);
	n[17]->next.push_back(NULL);
	n[18]->next.push_back(NULL);
	n[19]->next.push_back(n[18]);
	n[20]->next.push_back(n[19]);
	n[20]->next.push_back(n[18]);
	n[21]->next.push_back(n[20]);
	n[21]->next.push_back(NULL);
	n[22]->next.push_back(n[21]);
	n[23]->next.push_back(n[22]);
	n[23]->next.push_back(n[20]);
	n[23]->next.push_back(NULL);
	n[24]->next.push_back(NULL);
	n[25]->next.push_back(NULL);
	n[26]->next.push_back(n[25]);
	n[27]->next.push_back(NULL);
	n[28]->next.push_back(n[27]);
	n[29]->next.push_back(NULL);
	n[30]->next.push_back(NULL);
	n[31]->next.push_back(NULL);
	n[32]->next.push_back(NULL);
	n[33]->next.push_back(NULL);
	n[34]->next.push_back(NULL);
	n[35]->next.push_back(NULL);
	n[36]->next.push_back(NULL);
	n[37]->next.push_back(n[36]);
	n[38]->next.push_back(n[37]);
	n[39]->next.push_back(n[38]);
	n[40]->next.push_back(n[39]);
	n[41]->next.push_back(n[63]);
	n[41]->next.push_back(n[54]);
	n[41]->next.push_back(n[45]);
	n[41]->next.push_back(n[44]);
	n[41]->next.push_back(n[43]);
	n[41]->next.push_back(NULL);
	n[42]->next.push_back(n[41]);
	n[43]->next.push_back(n[42]);
	n[44]->next.push_back(n[63]);
	n[44]->next.push_back(n[54]);
	n[44]->next.push_back(n[45]);
	n[44]->next.push_back(n[44]);
	n[44]->next.push_back(n[43]);
	n[44]->next.push_back(NULL);
	n[45]->next.push_back(n[63]);
	n[45]->next.push_back(n[54]);
	n[45]->next.push_back(n[45]);
	n[45]->next.push_back(n[44]);
	n[45]->next.push_back(n[43]);
	n[45]->next.push_back(NULL);
	n[46]->next.push_back(n[63]);
	n[46]->next.push_back(n[54]);
	n[46]->next.push_back(n[45]);
	n[46]->next.push_back(n[44]);
	n[46]->next.push_back(n[43]);
	n[46]->next.push_back(NULL);
	n[47]->next.push_back(n[46]);
	n[48]->next.push_back(n[47]);
	n[49]->next.push_back(n[48]);
	n[50]->next.push_back(n[49]);
	n[51]->next.push_back(n[50]);
	n[51]->next.push_back(n[46]);
	n[52]->next.push_back(n[51]);
	n[53]->next.push_back(n[52]);
	n[54]->next.push_back(n[53]);
	n[55]->next.push_back(n[63]);
	n[55]->next.push_back(n[54]);
	n[55]->next.push_back(n[45]);
	n[55]->next.push_back(n[44]);
	n[55]->next.push_back(n[43]);
	n[55]->next.push_back(NULL);
	n[56]->next.push_back(n[59]);
	n[56]->next.push_back(n[55]);
	n[57]->next.push_back(n[56]);
	n[58]->next.push_back(n[57]);
	n[59]->next.push_back(n[58]);
	n[60]->next.push_back(n[59]);
	n[60]->next.push_back(n[55]);
	n[61]->next.push_back(n[60]);
	n[62]->next.push_back(n[61]);
	n[62]->next.push_back(n[55]);
	n[63]->next.push_back(n[62]);
	n[64]->next.push_back(n[63]);
	n[64]->next.push_back(n[54]);
	n[64]->next.push_back(n[45]);
	n[64]->next.push_back(n[44]);
	n[64]->next.push_back(n[43]);
	n[64]->next.push_back(NULL);
	n[65]->next.push_back(n[64]);
	n[66]->next.push_back(NULL);
	n[67]->next.push_back(NULL);
	n[68]->next.push_back(n[71]);
	n[68]->next.push_back(n[70]);
	n[68]->next.push_back(n[69]);
	n[68]->next.push_back(n[67]);
	n[69]->next.push_back(n[68]);
	n[70]->next.push_back(n[68]);
	n[71]->next.push_back(n[68]);
	n[72]->next.push_back(n[77]);
	n[72]->next.push_back(NULL);
	n[73]->next.push_back(n[72]);
	n[74]->next.push_back(n[73]);
	n[75]->next.push_back(n[73]);
	n[76]->next.push_back(n[73]);
	n[77]->next.push_back(n[76]);
	n[77]->next.push_back(n[75]);
	n[77]->next.push_back(n[74]);
	n[78]->next.push_back(n[77]);
	n[78]->next.push_back(NULL);
	n[79]->next.push_back(n[83]);
	n[79]->next.push_back(NULL);
	n[80]->next.push_back(n[79]);
	n[81]->next.push_back(n[80]);
	n[82]->next.push_back(n[80]);
	n[83]->next.push_back(n[82]);
	n[83]->next.push_back(n[81]);
	n[84]->next.push_back(n[83]);
	n[84]->next.push_back(NULL);
	n[85]->next.push_back(NULL);
	n[86]->next.push_back(n[85]);
	n[87]->next.push_back(n[86]);
	n[88]->next.push_back(n[86]);
	n[89]->next.push_back(n[86]);
	n[90]->next.push_back(n[86]);
	n[91]->next.push_back(n[86]);
	n[92]->next.push_back(n[91]);
	n[92]->next.push_back(n[90]);
	n[92]->next.push_back(n[89]);
	n[92]->next.push_back(n[88]);
	n[92]->next.push_back(n[87]);
	n[93]->next.push_back(n[92]);
	n[93]->next.push_back(NULL);
	n[94]->next.push_back(n[97]);
	n[94]->next.push_back(NULL);
	n[95]->next.push_back(n[94]);
	n[96]->next.push_back(n[95]);
	n[97]->next.push_back(n[96]);
	n[98]->next.push_back(n[97]);
	n[98]->next.push_back(NULL);
	n[99]->next.push_back(n[102]);
	n[99]->next.push_back(NULL);
	n[100]->next.push_back(n[99]);
	n[101]->next.push_back(n[100]);
	n[102]->next.push_back(n[101]);
	n[103]->next.push_back(n[102]);
	n[103]->next.push_back(NULL);
	n[104]->next.push_back(n[107]);
	n[104]->next.push_back(NULL);
	n[105]->next.push_back(n[104]);
	n[106]->next.push_back(n[105]);
	n[107]->next.push_back(n[106]);
	n[108]->next.push_back(n[107]);
	n[108]->next.push_back(NULL);
	n[109]->next.push_back(NULL);
	n[110]->next.push_back(n[109]);
	n[111]->next.push_back(n[110]);
	n[112]->next.push_back(n[110]);
	n[113]->next.push_back(n[110]);
	n[114]->next.push_back(n[110]);
	n[115]->next.push_back(n[110]);
	n[116]->next.push_back(n[110]);
	n[117]->next.push_back(n[116]);
	n[117]->next.push_back(n[115]);
	n[117]->next.push_back(n[114]);
	n[117]->next.push_back(n[113]);
	n[117]->next.push_back(n[112]);
	n[117]->next.push_back(n[111]);
	n[118]->next.push_back(n[117]);
	n[118]->next.push_back(NULL);
	n[119]->next.push_back(n[122]);
	n[119]->next.push_back(NULL);
	n[120]->next.push_back(n[119]);
	n[121]->next.push_back(n[120]);
	n[122]->next.push_back(n[121]);
	n[123]->next.push_back(n[122]);
	n[123]->next.push_back(NULL);
	n[124]->next.push_back(n[127]);
	n[124]->next.push_back(NULL);
	n[125]->next.push_back(n[124]);
	n[126]->next.push_back(n[125]);
	n[127]->next.push_back(n[126]);
	n[128]->next.push_back(n[127]);
	n[128]->next.push_back(NULL);
	n[129]->next.push_back(n[132]);
	n[129]->next.push_back(NULL);
	n[130]->next.push_back(n[129]);
	n[131]->next.push_back(n[130]);
	n[132]->next.push_back(n[131]);
	n[133]->next.push_back(n[132]);
	n[133]->next.push_back(NULL);
	n[134]->next.push_back(n[139]);
	n[134]->next.push_back(n[143]);
	n[134]->next.push_back(NULL);
	n[135]->next.push_back(n[134]);
	n[136]->next.push_back(n[135]);
	n[137]->next.push_back(n[136]);
	n[138]->next.push_back(n[137]);
	n[139]->next.push_back(n[138]);
	n[140]->next.push_back(n[139]);
	n[140]->next.push_back(n[143]);
	n[140]->next.push_back(NULL);
	n[141]->next.push_back(n[140]);
	n[142]->next.push_back(n[141]);
	n[143]->next.push_back(n[142]);
	n[144]->next.push_back(n[149]);
	n[144]->next.push_back(n[143]);
	n[144]->next.push_back(NULL);
	n[145]->next.push_back(n[144]);
	n[146]->next.push_back(n[145]);
	n[147]->next.push_back(n[146]);
	n[148]->next.push_back(n[147]);
	n[149]->next.push_back(n[148]);
	n[150]->next.push_back(n[149]);
	n[150]->next.push_back(n[143]);
	n[150]->next.push_back(NULL);
	n[151]->next.push_back(n[150]);
	n[152]->next.push_back(n[151]);
	n[153]->next.push_back(n[165]);
	n[153]->next.push_back(NULL);
	n[154]->next.push_back(n[153]);
	n[155]->next.push_back(n[154]);
	n[156]->next.push_back(n[161]);
	n[156]->next.push_back(n[155]);
	n[156]->next.push_back(n[165]);
	n[156]->next.push_back(NULL);
	n[157]->next.push_back(n[156]);
	n[158]->next.push_back(n[157]);
	n[159]->next.push_back(n[158]);
	n[160]->next.push_back(n[159]);
	n[161]->next.push_back(n[160]);
	n[162]->next.push_back(n[161]);
	n[162]->next.push_back(n[155]);
	n[162]->next.push_back(n[165]);
	n[162]->next.push_back(NULL);
	n[163]->next.push_back(n[162]);
	n[164]->next.push_back(n[163]);
	n[165]->next.push_back(n[164]);
	n[166]->next.push_back(n[165]);
	n[166]->next.push_back(NULL);
	n[167]->next.push_back(n[166]);
	n[168]->next.push_back(n[167]);
	n[169]->next.push_back(n[170]);
	n[169]->next.push_back(n[168]);
	n[169]->next.push_back(n[165]);
	n[169]->next.push_back(NULL);
	n[170]->next.push_back(n[169]);
	n[171]->next.push_back(n[176]);
	n[171]->next.push_back(n[170]);
	n[171]->next.push_back(n[168]);
	n[171]->next.push_back(n[165]);
	n[171]->next.push_back(NULL);
	n[172]->next.push_back(n[171]);
	n[173]->next.push_back(n[172]);
	n[174]->next.push_back(n[173]);
	n[175]->next.push_back(n[174]);
	n[176]->next.push_back(n[175]);
	n[177]->next.push_back(n[176]);
	n[177]->next.push_back(n[170]);
	n[177]->next.push_back(n[168]);
	n[177]->next.push_back(n[165]);
	n[177]->next.push_back(NULL);
	n[178]->next.push_back(n[177]);
	n[179]->next.push_back(n[178]);
	n[180]->next.push_back(NULL);
	n[181]->next.push_back(n[180]);
	n[182]->next.push_back(n[181]);
	n[183]->next.push_back(n[181]);
	n[184]->next.push_back(n[181]);
	n[185]->next.push_back(n[181]);
	n[186]->next.push_back(n[181]);
	n[187]->next.push_back(n[181]);
	n[188]->next.push_back(n[181]);
	n[189]->next.push_back(n[181]);
	n[190]->next.push_back(n[181]);
	n[191]->next.push_back(n[181]);
	n[192]->next.push_back(n[181]);
	n[193]->next.push_back(n[181]);
	n[194]->next.push_back(n[181]);
	n[195]->next.push_back(n[181]);
	n[196]->next.push_back(n[181]);
	n[197]->next.push_back(n[181]);
	n[198]->next.push_back(n[181]);
	n[199]->next.push_back(n[198]);
	n[199]->next.push_back(n[197]);
	n[199]->next.push_back(n[196]);
	n[199]->next.push_back(n[195]);
	n[199]->next.push_back(n[194]);
	n[199]->next.push_back(n[193]);
	n[199]->next.push_back(n[192]);
	n[199]->next.push_back(n[191]);
	n[199]->next.push_back(n[190]);
	n[199]->next.push_back(n[189]);
	n[199]->next.push_back(n[188]);
	n[199]->next.push_back(n[187]);
	n[199]->next.push_back(n[186]);
	n[199]->next.push_back(n[185]);
	n[199]->next.push_back(n[184]);
	n[199]->next.push_back(n[183]);
	n[199]->next.push_back(n[182]);
	n[200]->next.push_back(n[199]);
	n[201]->next.push_back(NULL);
	n[202]->next.push_back(NULL);
	n[203]->next.push_back(n[202]);
	n[203]->next.push_back(n[201]);
	n[204]->next.push_back(n[203]);
	n[205]->next.push_back(n[204]);
	n[206]->next.push_back(n[218]);
	n[206]->next.push_back(n[205]);
	n[207]->next.push_back(n[218]);
	n[207]->next.push_back(n[205]);
	n[208]->next.push_back(n[207]);
	n[208]->next.push_back(n[206]);
	n[209]->next.push_back(n[208]);
	n[210]->next.push_back(n[209]);
	n[211]->next.push_back(n[210]);
	n[212]->next.push_back(n[211]);
	n[213]->next.push_back(n[212]);
	n[214]->next.push_back(n[213]);
	n[215]->next.push_back(n[214]);
	n[216]->next.push_back(n[215]);
	n[217]->next.push_back(n[216]);
	n[218]->next.push_back(n[217]);
	n[219]->next.push_back(n[218]);
	n[219]->next.push_back(n[205]);
	n[220]->next.push_back(n[218]);
	n[220]->next.push_back(n[205]);
	n[221]->next.push_back(n[220]);
	n[221]->next.push_back(n[219]);
	n[222]->next.push_back(n[221]);
	n[223]->next.push_back(n[222]);
	n[224]->next.push_back(n[223]);
	n[225]->next.push_back(n[224]);
	n[226]->next.push_back(n[225]);
	n[227]->next.push_back(n[226]);
	n[228]->next.push_back(n[227]);
	n[229]->next.push_back(NULL);
	n[230]->next.push_back(NULL);
	n[231]->next.push_back(n[230]);
	n[231]->next.push_back(n[229]);
	n[232]->next.push_back(n[231]);
	n[233]->next.push_back(n[232]);
	n[234]->next.push_back(n[233]);
	n[235]->next.push_back(n[234]);
	n[236]->next.push_back(n[235]);
	n[237]->next.push_back(n[236]);
	n[238]->next.push_back(n[237]);
	n[239]->next.push_back(NULL);
	n[240]->next.push_back(n[239]);
	n[241]->next.push_back(n[240]);
	n[242]->next.push_back(NULL);
	n[243]->next.push_back(n[242]);
	n[244]->next.push_back(n[243]);
	n[245]->next.push_back(NULL);
	n[246]->next.push_back(NULL);
	n[247]->next.push_back(NULL);
	n[248]->next.push_back(n[247]);
	n[249]->next.push_back(n[248]);
	n[250]->next.push_back(n[249]);
	n[250]->next.push_back(n[247]);
	n[251]->next.push_back(n[250]);
	n[252]->next.push_back(NULL);
	n[253]->next.push_back(n[252]);
	n[254]->next.push_back(n[253]);
	n[255]->next.push_back(NULL);
	n[256]->next.push_back(n[255]);
	n[257]->next.push_back(n[256]);
	n[258]->next.push_back(NULL);
	n[259]->next.push_back(n[258]);
	n[260]->next.push_back(n[261]);
	n[260]->next.push_back(n[259]);
	n[261]->next.push_back(n[260]);
	n[262]->next.push_back(n[261]);
	n[262]->next.push_back(n[259]);
	n[263]->next.push_back(n[262]);
	n[263]->next.push_back(n[259]);
	n[264]->next.push_back(n[263]);
	n[265]->next.push_back(NULL);
	n[266]->next.push_back(n[265]);
	n[267]->next.push_back(n[266]);
	n[268]->next.push_back(n[267]);
	n[269]->next.push_back(n[272]);
	n[269]->next.push_back(n[268]);
	n[270]->next.push_back(n[269]);
	n[271]->next.push_back(n[270]);
	n[272]->next.push_back(n[271]);
	n[273]->next.push_back(n[272]);
	n[273]->next.push_back(n[268]);
	n[274]->next.push_back(n[273]);
	n[275]->next.push_back(n[274]);
	n[275]->next.push_back(n[268]);
	n[276]->next.push_back(n[275]);
	n[277]->next.push_back(n[276]);
	n[278]->next.push_back(n[277]);
	n[279]->next.push_back(n[278]);
	n[280]->next.push_back(n[279]);
	n[281]->next.push_back(n[280]);
	n[282]->next.push_back(n[281]);
	n[282]->next.push_back(n[277]);
	n[283]->next.push_back(n[282]);
	n[284]->next.push_back(NULL);
	n[285]->next.push_back(n[288]);
	n[285]->next.push_back(n[284]);
	n[286]->next.push_back(n[285]);
	n[287]->next.push_back(n[286]);
	n[288]->next.push_back(n[287]);
	n[289]->next.push_back(n[288]);
	n[289]->next.push_back(n[284]);
	n[290]->next.push_back(n[289]);
	n[291]->next.push_back(n[290]);
	n[292]->next.push_back(n[291]);
	n[293]->next.push_back(n[292]);
	n[294]->next.push_back(n[293]);
	n[295]->next.push_back(NULL);
	n[296]->next.push_back(n[298]);
	n[296]->next.push_back(n[297]);
	n[296]->next.push_back(n[295]);
	n[297]->next.push_back(n[296]);
	n[298]->next.push_back(n[296]);
	n[299]->next.push_back(n[298]);
	n[299]->next.push_back(n[297]);
	n[299]->next.push_back(n[295]);

	grammar.rules[0].start.push_back(n[299]);
	grammar.rules[1].start.push_back(n[294]);
	grammar.rules[2].start.push_back(n[283]);
	grammar.rules[3].start.push_back(n[152]);
	grammar.rules[4].start.push_back(n[16]);
	grammar.rules[4].start.push_back(n[15]);
	grammar.rules[4].start.push_back(n[14]);
	grammar.rules[4].start.push_back(n[12]);
	grammar.rules[4].start.push_back(n[11]);
	grammar.rules[4].start.push_back(n[7]);
	grammar.rules[4].start.push_back(n[5]);
	grammar.rules[4].start.push_back(n[4]);
	grammar.rules[5].start.push_back(n[179]);
	grammar.rules[6].start.push_back(n[264]);
	grammar.rules[7].start.push_back(n[257]);
	grammar.rules[7].start.push_back(n[254]);
	grammar.rules[7].start.push_back(n[251]);
	grammar.rules[7].start.push_back(n[246]);
	grammar.rules[7].start.push_back(n[245]);
	grammar.rules[7].start.push_back(n[244]);
	grammar.rules[7].start.push_back(n[241]);
	grammar.rules[8].start.push_back(n[133]);
	grammar.rules[9].start.push_back(n[228]);
	grammar.rules[10].start.push_back(n[238]);
	grammar.rules[11].start.push_back(n[200]);
	grammar.rules[12].start.push_back(n[128]);
	grammar.rules[13].start.push_back(n[123]);
	grammar.rules[14].start.push_back(n[118]);
	grammar.rules[15].start.push_back(n[108]);
	grammar.rules[16].start.push_back(n[103]);
	grammar.rules[17].start.push_back(n[98]);
	grammar.rules[18].start.push_back(n[93]);
	grammar.rules[19].start.push_back(n[84]);
	grammar.rules[20].start.push_back(n[78]);
	grammar.rules[21].start.push_back(n[71]);
	grammar.rules[21].start.push_back(n[70]);
	grammar.rules[21].start.push_back(n[69]);
	grammar.rules[21].start.push_back(n[67]);
	grammar.rules[22].start.push_back(n[66]);
	grammar.rules[22].start.push_back(n[65]);
	grammar.rules[23].start.push_back(n[34]);
	grammar.rules[23].start.push_back(n[33]);
	grammar.rules[23].start.push_back(n[32]);
	grammar.rules[23].start.push_back(n[31]);
	grammar.rules[24].start.push_back(n[40]);
	grammar.rules[24].start.push_back(n[35]);
	grammar.rules[25].start.push_back(n[30]);
	grammar.rules[25].start.push_back(n[29]);
	grammar.rules[26].start.push_back(n[28]);
	grammar.rules[26].start.push_back(n[26]);
	grammar.rules[26].start.push_back(n[24]);
	grammar.rules[27].start.push_back(n[17]);
	grammar.rules[28].start.push_back(n[23]);
}

}

